import { listen } from "@tauri-apps/api/event";
import clsx from "clsx";
import { useEffect, useState } from "react";
import { generateCatPortrait, readPortraitBytes, saveCat } from "../lib/api";
import type { Cat, CatType } from "../lib/types";
import { newId } from "../lib/util";
import { useViewStore } from "../lib/viewStore";

interface PortraitProgress {
	cat_id: string;
	partial_index: number | null;
	is_final: boolean;
	data_url: string;
}

interface CatChoice {
	type: CatType;
	displayName: string;
	tagline: string;
	hint: string;
	emoji: string;
	visibleTraits: string[];
	hiddenTraits: string[];
}

// Emoji placeholders shown on the picker cards. The real cat portrait is
// generated by `gpt-image-2` only after the user picks one, so we don't burn
// three image-gen calls on first load.
const CHOICES: CatChoice[] = [
	{
		type: "orange_fat",
		displayName: "Mango",
		tagline: "An orange situation.",
		hint: "Food-motivated. Very dramatic. Will tell you exactly what they want.",
		emoji: "🐈",
		visibleTraits: ["theatrical", "snack-oriented", "vocal"],
		hiddenTraits: ["needs reassurance", "secretly tender"],
	},
	{
		type: "void",
		displayName: "Pluto",
		tagline: "Something quiet sat near you.",
		hint: "Quiet. Watching. Affectionate, eventually.",
		emoji: "🐈‍⬛",
		visibleTraits: ["observant", "still", "mysterious"],
		hiddenTraits: ["very loyal", "playful at night"],
	},
	{
		type: "scrungly_street",
		displayName: "Bean",
		tagline: "Slightly scuffed. Definitely yours.",
		hint: "Scrappy. Loud. Suspiciously loyal.",
		emoji: "😼",
		visibleTraits: ["chaotic", "scrappy", "alert"],
		hiddenTraits: ["resilient", "weirdly tender about routine"],
	},
];

export function CatAdoption() {
	const setView = useViewStore((s) => s.setView);
	const [pending, setPending] = useState<CatType | null>(null);
	const [error, setError] = useState<string | null>(null);
	const [pendingCatId, setPendingCatId] = useState<string | null>(null);
	const [partialDataUrl, setPartialDataUrl] = useState<string | null>(null);
	const [revealed, setRevealed] = useState<{
		choice: CatChoice;
		dataUrl: string;
		cat: Cat;
	} | null>(null);

	// Stream partial frames from the streaming gpt-image-2 call. We keep the
	// most recent partial in state and render it inside the loading card so
	// the user sees the cat resolve into focus on stage.
	useEffect(() => {
		let unlisten: (() => void) | undefined;
		(async () => {
			unlisten = await listen<PortraitProgress>(
				"cat-portrait-progress",
				(event) => {
					if (pendingCatId !== null && event.payload.cat_id !== pendingCatId) {
						return;
					}
					setPartialDataUrl(event.payload.data_url);
				},
			);
		})();
		return () => unlisten?.();
	}, [pendingCatId]);

	const adopt = async (choice: CatChoice) => {
		setPending(choice.type);
		setError(null);
		setPartialDataUrl(null);
		try {
			const catId = newId("cat");
			setPendingCatId(catId);
			const portrait = await generateCatPortrait({
				cat_id: catId,
				cat_type: choice.type,
				mood: "content",
				independence_tier: 0,
				accessory_set_hash: "v1",
				skills: [],
			});
			const b64 = await readPortraitBytes(portrait.path);
			const cat: Cat = {
				id: catId,
				type: choice.type,
				name: choice.displayName,
				visible_traits: choice.visibleTraits,
				hidden_traits: choice.hiddenTraits,
				needs: {
					hunger: 0.3,
					boredom: 0.3,
					loneliness: 0.2,
					dirty_litter: 0.1,
					play_drive: 0.4,
					attention: 0.5,
				},
				mood: "content",
				independence_level: 0,
				skills: [],
				items: [],
				story_events: [],
				portrait_path: portrait.path,
			};
			await saveCat(cat);
			setRevealed({ choice, dataUrl: `data:image/png;base64,${b64}`, cat });
		} catch (e) {
			setError(e instanceof Error ? e.message : String(e));
		} finally {
			setPending(null);
			setPendingCatId(null);
			setPartialDataUrl(null);
		}
	};

	if (revealed) {
		return (
			<div className="adoption">
				<div className="adoption-reveal">
					<div className="reveal-frame">
						<img src={revealed.dataUrl} alt={revealed.choice.displayName} />
					</div>
					<h1>{revealed.choice.displayName} chose you.</h1>
					<p className="lede">{revealed.choice.tagline}</p>
					<p className="muted">{revealed.choice.hint}</p>
					<button
						type="button"
						className="primary"
						onClick={() => setView("dashboard")}
					>
						Take me home
					</button>
				</div>
			</div>
		);
	}

	return (
		<div className="adoption">
			<header className="adoption-header">
				<h1>Three cats came by.</h1>
				<p className="muted">One of them will choose you.</p>
			</header>
			<div className="cat-grid">
				{CHOICES.map((choice) => (
					<button
						type="button"
						key={choice.type}
						className={clsx("cat-card", pending === choice.type && "loading")}
						onClick={() => adopt(choice)}
						disabled={pending !== null}
					>
						<div className="cat-card-art">
							{pending === choice.type && partialDataUrl ? (
								<img
									src={partialDataUrl}
									alt={`${choice.displayName} appearing`}
									className="cat-card-partial"
								/>
							) : (
								<span
									className="cat-card-emoji"
									role="img"
									aria-label={choice.displayName}
								>
									{choice.emoji}
								</span>
							)}
						</div>
						<div className="cat-card-meta">
							<div className="cat-card-name">{choice.displayName}</div>
							<div className="cat-card-tagline">{choice.tagline}</div>
							<div className="cat-card-hint">{choice.hint}</div>
						</div>
						{pending === choice.type ? (
							<div className="cat-card-pending">Drawing your cat…</div>
						) : null}
					</button>
				))}
			</div>
			{error ? <p className="error">{error}</p> : null}
		</div>
	);
}
